name: xyz_project
description: "Bug WhatsApp Crasher"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  video_player: ^2.8.2
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.5.0
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  syncfusion_flutter_charts: ^26.2.12  # <-- tambah ini

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon.jpg
  image_path_ios: assets/icon/icon/icon.jpg
  image_path: assets/icon/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/banner.mp4
  fonts:
    - family: Rajdhani
      fonts:
       - asset: fonts/Rajdhani-Regular.ttf
         weight: 400
       - asset: fonts/Rajdhani-Medium.ttf
         weight: 500
       - asset: fonts/Rajdhani-Bold.ttf
         weight: 700
       - asset: fonts/Rajdhani-SemiBold.ttf
         weight: 600
       - asset: fonts/Rajdhani-Bold.ttf
         weight: 800
